name: release-please

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go

  build-and-upload:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - name: Build and package
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          ext=""
          if [ "${GOOS}" = "windows" ]; then ext=".exe"; fi
          GOOS=${GOOS} GOARCH=${GOARCH} go build -o dist/bloom-${GOOS}-${GOARCH}${ext}
          cd dist
          zip bloom-${GOOS}-${GOARCH}.zip bloom-${GOOS}-${GOARCH}${ext}
          cd ..
      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} dist/bloom-${{ matrix.goos }}-${{ matrix.goarch }}.zip
